#########################
## Sass Lint File
#########################
# Linter Options
options:
  # Don't merge default rules
  merge-default-rules: false
  # Set the formatter to 'stylish'
  formatter: stylish
  # Raise an error if more than 50 warnings are generated
  max-warnings: 50
# Rule Configuration
rules:
  border-zero:
    - 1
    - convention: zero
  extends-before-declarations: 2
  extends-before-mixins: 2
  final-newline:
    - 1
    - include: true
  hex-notation:
    - 2
    - style: lowercase
  indentation:
    - 2
    - size: 2
  leading-zero:
    - 1
    - include: false
  mixins-before-declarations: 1
  mixin-name-format:
    - 1
    - allow-leading-underscore: true
      convention: hyphenatedlowercase
  nesting-depth:
    - 1
    - max-depth: 5
  no-css-comments: 1
  no-debug: 1
  no-ids: 2
  no-important: 1
  no-invalid-hex: 1
  no-mergeable-selectors: 1
  no-misspelled-properties: 1
  no-trailing-zero: 1
  no-transition-all: 0
  no-vendor-prefixes: 1
  no-warn: 1
  placeholder-in-extend: 1
  placeholder-name-format:
    - 1
    - convention: hyphenatedlowercase
  property-sort-order:
    - 1
    - ignore-custom-properties: true
  variable-for-property:
    - 1
    - properties:
        - background-color
        - color
        - font
        - content